TC_ARCH = 88f5281
TC_VERS = 3.1
TC_FIRMWARE = 3.1-1594
TC_KERNEL = 2.6.15
TC_GLIBC = 2.3

TC_DIST = gcc343_glibc232_88f5281
TC_EXT = tgz
TC_DIST_SITE_PATH = Marvell%2088F5281%20Linux%202.6.15

TC_TARGET = arm-marvell-linux-gnu
TC_SYSROOT = $(TC_TARGET)/libc
TC_LIBRARY = $(TC_SYSROOT)/usr/lib

include ../../mk/spksrc.tc.mk
